# The full list of country/competition codes
country_codes = {
    'Spain': 'ESP',
    'Italy': 'ITA',
    'Germany': 'GER',
    'France': 'FRA',
    'England': 'ENG',
    'Portugal': 'POR',
    'Netherlands': 'NED',
    'Belgium': 'BEL',
    'Scotland': 'SCO',
    'Turkey': 'TUR',
    'Czechia': 'CZE',
    'Greece': 'GRE',
    'Switzerland': 'SUI',
    'Denmark': 'DEN',
    'Sweden': 'SWE',
    'Austria': 'AUT',
    'Ukraine': 'UKR',
    'Croatia': 'CRO',
    'Serbia': 'SRB',
    'Slovakia': 'SVK',
    'Norway': 'NOR',
    'Russia': 'RUS',
    'Poland': 'POL',
    'Israel': 'ISR',
    'Romania': 'ROU',
    'Azrbaijan': 'AZE',
    'Ukraine': 'UKR',
    'Serbia': 'SRB',
    'Bulgaria': 'BUL',
    'Cyprus': 'CYP',
    'Hungary': 'HUN',
    'Moldova': 'MDA',
    'Slovenia': 'SVN',
    'Slovakia': 'SLK',
    'Kazakhstan': 'KAZ',
    'Finland': 'FIN',
    'Ireland': 'IRL',
    'Iceland': 'ISL',
    'Lithuania': 'LIT',
    'Latvia': 'LAT',
    'Estonia': 'EST',
    'Luxembourg': 'LUX',
    'Malta': 'MLT',
    'Andorra': 'AND',
    'San Marino': 'SMR',
    'Gibraltar': 'GIB',
    'Georgia': 'GEO',
    'Armenia': 'ARM',
    'Faroe Islands': 'FAR',
    'Wales': 'WAL',
    'Northern Ireland': 'NIR',
    'Belarus': 'BLR',
    'Albania': 'ALB',
    'Macedonia': 'MAC',
    'Montenegro': 'MNE',
    'Kosovo': 'KOS',
    'Iceland': 'ISL',
    'Bosnia-Herzegovina': 'BHZ',
    'Champions League': 'UCL',
    'Europa League': 'UEL',
    'Europa Conference League': 'ECL',
    'Europe': 'All'
}
